import {
  FileBadge,
  Scale,
  TrendingUp,
  Truck,
  Warehouse,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const objections = [
  {
    icon: 'spreads' as const,
    question: 'Are your spreads actually competitive for smaller volume orders?',
    answer:
      'Our institutional liquidity lines deliver the same tight bid/ask spreads regardless of transaction size tied directly to live global spot rates with zero markup layered on top.',
  },
  {
    icon: 'purity' as const,
    question: 'How do I know the purity certification is independent?',
    answer:
      "Every assay certificate is generated by an independent, third-party accredited laboratory. The certifying body's name appears on every document not just ours.",
  },
  {
    icon: 'storage' as const,
    question: 'What happens to my metal if something goes wrong during storage?',
    answer:
      'Your allocated holdings are covered under a comprehensive all-risk insurance policy at full replacement value. Your metal is segregated never co-mingled - and independently auditable at any time.',
  },
  {
    icon: 'execution' as const,
    question: 'How quickly can a large order actually be executed?',
    answer:
      'Our deep capital reserves and continuous inventory position allow immediate large-volume execution at a fixed spot rate. Your dealer confirms, you approve, settlement follows - no external sourcing delays.',
  },
  {
    icon: 'compliance' as const,
    question:
      'Is Dipanjali regulated and compliant for institutional counterparties?',
    answer:
      'All operations run under applicable Indian regulatory frameworks with full AML-CFT protocols at every stage. Our KYC onboarding meets the same international standards we apply to every party we transact with.',
  },
  {
    icon: 'supply' as const,
    question: 'Can you handle ongoing supply requirements for manufacturers?',
    answer:
      'Yes. We structure forward pricing arrangements, priority inventory allocation, and dedicated account management for manufacturers and industrial processors with recurring monthly requirements.',
  },
];

type ObjectionIconType = (typeof objections)[number]['icon'];

const objectionIcons: Record<ObjectionIconType, LucideIcon> = {
  spreads: TrendingUp,
  purity: FileBadge,
  storage: Warehouse,
  execution: Zap,
  compliance: Scale,
  supply: Truck,
};

function ObjectionIcon({ type }: { type: ObjectionIconType }) {
  const Icon = objectionIcons[type];
  return (
    <span className="industry-objections__icon" aria-hidden="true">
      <Icon />
    </span>
  );
}

export default function IndustryObjectionsSection() {
  return (
    <section
      id="objections"
      className="industry-objections"
      aria-label="Addressing industry objections"
    >
      <div className="industry-objections__inner">
        <header className="industry-objections__header">
          <p className="industry-objections__eyebrow">COMMON QUESTIONS</p>
          <h2 className="industry-objections__title">
            ADDRESSING INDUSTRY OBJECTIONS
          </h2>
          <span className="industry-objections__rule" aria-hidden="true" />
        </header>

        <ul className="industry-objections__grid">
          {objections.map((item) => (
            <li key={item.question} className="industry-objections__card">
              <ObjectionIcon type={item.icon} />
              <h3 className="industry-objections__question">{item.question}</h3>
              <span className="industry-objections__divider" aria-hidden="true" />
              <p className="industry-objections__answer">{item.answer}</p>
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}
