import Image from 'next/image';

const objections = [
  {
    tone: 'white' as const,
    iconSrc:
      'https://assets.nexuses.xyz/Mask_group__11__1789730986984_j83e.png',
    question: 'Are your spreads actually competitive for smaller volume orders?',
    answer:
      'Our institutional liquidity lines deliver the same tight bid/ask spreads regardless of transaction size tied directly to live global spot rates with zero markup layered on top.',
  },
  {
    tone: 'sage' as const,
    iconSrc:
      'https://assets.nexuses.xyz/Mask_group__12__1789730986984_i6c5.png',
    question: 'How do I know the purity certification is independent?',
    answer:
      "Every assay certificate is generated by an independent, third-party accredited laboratory. The certifying body's name appears on every document not just ours.",
  },
  {
    tone: 'gold' as const,
    iconSrc:
      'https://assets.nexuses.xyz/Mask_group__13__1789730986984_9x5e.png',
    question: 'How quickly can a large order actually be executed?',
    answer:
      'Our deep capital reserves and continuous inventory position allow immediate large-volume execution at a fixed spot rate. Your dealer confirms, you approve, settlement follows - no external sourcing delays.',
  },
  {
    tone: 'white' as const,
    iconSrc:
      'https://assets.nexuses.xyz/Mask_group__14__1789730986984_0gku.png',
    question:
      'Is Dipanjali regulated and compliant for institutional counterparties?',
    answer:
      'All operations run under applicable UAE regulatory frameworks with full AML-CFT protocols at every stage. Our KYC onboarding meets the same international standards we apply to every party we transact with.',
  },
  {
    tone: 'sage' as const,
    iconSrc:
      'https://assets.nexuses.xyz/Mask_group__15__1789730986984_8l0u.png',
    question: 'Can you handle ongoing supply requirements for manufacturers?',
    answer:
      'Yes. We structure forward pricing arrangements, priority inventory allocation, and dedicated account management for manufacturers and industrial processors with recurring monthly requirements.',
  },
];

export default function IndustryObjectionsSection() {
  return (
    <section
      id="objections"
      className="industry-objections"
      aria-label="Addressing industry objections"
    >
      <div className="industry-objections__inner">
        <header className="industry-objections__header">
          <p className="industry-objections__eyebrow">COMMON QUESTIONS</p>
          <h2 className="industry-objections__title">
            ADDRESSING INDUSTRY OBJECTIONS
          </h2>
          <span className="industry-objections__rule" aria-hidden="true" />
        </header>

        <ul className="industry-objections__grid">
          {objections.map((item) => (
            <li
              key={item.question}
              className={`industry-objections__card industry-objections__card--${item.tone}`}
            >
              <span className="industry-objections__icon" aria-hidden="true">
                <Image
                  className="industry-objections__icon-img"
                  src={item.iconSrc}
                  alt=""
                  width={56}
                  height={56}
                />
              </span>
              <h3 className="industry-objections__question">{`\u2018${item.question}\u2019`}</h3>
              <span
                className="industry-objections__divider"
                aria-hidden="true"
              />
              <p className="industry-objections__answer">{item.answer}</p>
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}
